### ISSUE TITLE
UnboundLocalError in tut_concorde.py

### ISSUE THREAD

**Issue by JotaHG** [suavecode/Tutorials#17]
When I tried running the example code, I received this error message:

**Comment by JotaHG** [comment]
> When I tried running the example code, I received this error message:

**Comment by JotaHG** [comment]
When I tried running the example code, I received this error message:

>   File "C:\Users\jota-\Anaconda3\lib\site-packages\suave-2.0.0-py3.7.egg\SUAVE\Methods\Aerodynamics\Supersonic_Zero\Drag\wave_drag_volume.py", line 44, in wave_drag_volume
    LE_sweep = main_wing.sweeps.leading_edge / Units.deg
**UnboundLocalError: local variable 'main_wing' referenced before assignment**

How could I solve this? 

Thanks in advance!

**Comment by planes** [comment]
Hi,
It looks like you're using our develop branch (or some other branch) with the release tutorials.

Our tutorial releases are only intended to work with the corresponding SUAVE release. If you're using a git client you can check out the master branch.

-Emilio

**Comment by JotaHG** [comment]
Hi,

Thank you for your help!!
Now I'm having another trouble. After I install the standard version 2.0.0 and execute tut_mission_B737.py example, I've got this error message:

>   File "C:\Users\jota-\Anaconda3\lib\site-packages\numpy\__init__.py", line 220, in __getattr__
    "{!r}".format(__name__, attr))
**AttributeError: module 'numpy' has no attribute 'rank'**
