### ISSUE TITLE
problem with OpenVSP compgeom file format

### ISSUE THREAD

**Issue by lgmg** [suavecode/Tutorials#6]
Hi all,
First, thank you for this powerful tool and the tutorials.
 
I am trying to lauch the BWB_CFD tutorial and SUAVE returns an error  (installed : VSP 3.11.0). 
I am under the impression that in get_vsp_areas (Input_Output/OpenVSP/get_vsp_areas.py) the reading of the file Unnamed_CompGeom.csv crashes. The file format may have changed. Here is the contents of the file :
```
Name, Theo_Area, Wet_Area, Theo_Vol, Wet_Vol
main_wing0,3124.876446,3124.876446,3801.754585,3801.754585
Totals,3124.876446,3124.876446,3801.754585,3801.754585

Tag_Name, Tag_Theo_Area, Tag_Wet_Area
main_wing0,1562.438223,1562.438223
main_wing1,1562.438223,1562.438223
```

The subsurfs calculations added (I don't know how to disable this calculation from the python code)

I changed the reading of the file (stop when only one element in split string = '\n') : I supposed that the area is one calculated in the first section and not subsurfs.

With this modification, the result I obtained  :
```
# AoA Mach CL CD
0.00000000 0.30000000 0.00249014 0.00112912
0.00000000 0.50000000 0.00286961 0.00149279
0.00000000 0.70000000 0.00377595 0.00250259
0.00000000 0.85000000 0.00695390 0.00971161
0.05235988 0.30000000 0.20416800 0.00426807
0.05235988 0.50000000 0.21541200 0.00524543
0.05235988 0.70000000 0.24162500 0.00819756
0.05235988 0.85000000 0.29267600 0.02799510
0.10471976 0.30000000 0.40301700 0.01387190
0.10471976 0.50000000 0.42178900 0.01712480
0.10471976 0.70000000 0.45752300 0.02798540
0.10471976 0.85000000 0.50738500 0.06668510
```
is different from the one provided :
```
0.00000000 0.30000000 0.00357426 0.00198925
0.00000000 0.50000000 0.00385438 0.00262971
0.00000000 0.70000000 0.00471753 0.00444076
0.00000000 0.85000000 0.00856885 0.01859320
0.05235988 0.30000000 0.20620500 0.00821743
0.05235988 0.50000000 0.21761550 0.01013710
0.05235988 0.70000000 0.24444750 0.01578280
0.05235988 0.85000000 0.29654400 0.05575920
0.10471976 0.30000000 0.40600150 0.02727500
0.10471976 0.50000000 0.42532150 0.03379330
0.10471976 0.70000000 0.46278650 0.05568500
0.10471976 0.85000000 0.51038000 0.13394200
```
Can you confirm the provided data with the new OpenVSP application ?

**Comment by timdmacdo** [comment]
Hi Igmg,

Thanks for pointing this out. It is likely that there was a format change since this was last tested with OpenVSP 3.9. It sounds like you have a fix for that one, but I'll look into the CFD results that you're getting later today.

Tim

**Comment by lgmg** [comment]
The easiest way to solve the format issue is to find how to uncheck the subsurfs calculation option (like halfmesh). Indeed, in vsp, in the compgeomdialog box, one can uncheck the subsurfs calculation.

By the way, thank you for your fast answer.
Leang-Ming (lgmg)

**Comment by timdmacdo** [comment]
We've checked results with 3.9 and 3.11. Our results in both cases are closer to yours than the file on Github. My guess is that the file uploaded is a little older than the BWB script and the BWB script was modified a bit before it was uploaded. There are still some small differences. Since the the mesh is relatively coarse, I assume these are due differences in how the mesh is randomly generated or our versions of Gmsh/SU2. 

For reference, here are my results with 3.11:

```
# AoA Mach CL CD
0.00000000 0.30000000 0.00239705 0.00119897
0.00000000 0.50000000 0.00270429 0.00154102
0.00000000 0.70000000 0.00347776 0.00251173
0.00000000 0.85000000 0.00687255 0.00943016
0.05235988 0.30000000 0.20502800 0.00431092
0.05235988 0.50000000 0.21630300 0.00529101
0.05235988 0.70000000 0.24248200 0.00816603
0.05235988 0.85000000 0.29367100 0.02793530
0.10471976 0.30000000 0.40510800 0.01390160
0.10471976 0.50000000 0.42398100 0.01721060
0.10471976 0.70000000 0.45916700 0.02808640
0.10471976 0.85000000 0.50685200 0.06684880
```

We won't add the area format change until our next release, but I'll leave this issue open and make a note of it on our tutorial. Thanks for letting us know.

**Comment by lgmg** [comment]
Thank you having taken the time to launch this calculation and for your support. 

_Bonne Journée_.
Leang-Ming

**Comment by timdmacdo** [comment]
This issue has been resolved. Also, the relevant tutorial has been taken down for some testing with new releases of other code bases.
